name: Unit Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup Scala 3
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"

      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: Build and Test
        run: |
          sbt -v +test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
        shell: bash